version 2.1

jobs:

  build:
    docker:
      - image: circle ci/ 3.18.0
    steps:
      - run: npm i
      - run: npm run lint

  test:
    docker:
      - image: circle ci 3.18.0
    steps:
      - run: npm i
      - run: npm run test
  
  analyse:
    docker:
      - image: npm i
      - run: npm run 



workflows:
  my-workflow:
    jobs:
      - build
      - test:
          requires: [build]
      - analyse:
          requires: [test]
